config/routes.rb
Bismillah::Application.routes.draw do
  resources :programs

end

app/models/program.rb
class Program < ActiveRecord::Base
  attr_accessible :active, :content, :title
  
  validates :title, presence: true
  validates :content, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  def index
    @program = Program.all(order: "created_at DESC")
  end

  def show
    @program = Program.find(params[:id])
  end
  
  def create
    @program = Program.new(params[:program])
    
    if @program.save
      redirect_to action: 'index'
    else
      render 'new'
    end
  end
  
  def new 
    @program = Program.new
  end
  

  def edit
        @program = Program.find params[:id]
  end
  
  def update
    @program = Program.find params[:id]

      respond_to do |format|
        if @program.update_attributes(params[:program])
          format.html { redirect_to(@program, :notice => 'Program basariyla guncellendi') }
          format.json { respond_with_bip(@program) }
        else
          format.html { render :action => "edit" }
          format.json { respond_with_bip(@program) }
        end
      end
  end
  

  def destroy
    @program = Program.find(params[:id])
    
    @program.destroy
    
    redirect_to action: 'index'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bismillah</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <script type="text/javascript" charset="utf-8">
  $(document).ready(function() {
    /* Activating Best In Place */
    jQuery(".best_in_place").best_in_place();
  });
  	
  </script>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/programs/destroy.html.erb
<h1>Programs#destroy</h1>
<p>Find me in app/views/programs/destroy.html.erb</p>

app/views/programs/edit.html.erb
<html>
<head>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8">
	<title>Program Duzenle</title>
</head>
<body>
	

	<%= form_for(@program) do |p|%>
	<%= p.label :title%><br />
	<%= p.text_field :title, :size =>"55x10" %><br />
	
	<%= p.label :content%><br />
	<%= p.text_area :content, :size =>"40x10" %><br /><br />
	
	<%= p.label :active%><br />
	<%= p.text_field :active, :size =>"1" %><br />
	
	<%= p.submit %>
	
	<% end %>
	
	<%= debug @program %>
	
</body>
</html>

app/views/programs/index.html.erb
<html>
<head>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8">
	<title>Program index</title>
</head>
<body>
	
	<%= link_to "Yeni program", new_program_path %>
	
	<% @program.each do |p| %>
	<ul>
		<li><%= p.title %></li>
		<%= link_to "Delete", p, confirm: "Silmek istediginize emin misiniz?", method: :delete%>
		
		<%= link_to "Edit", edit_program_path(p)%>
	</ul>
	<% end %>
	
	<%= debug @program %>
</body>
</html>

app/views/programs/new.html.erb
<html>
<head>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8">
	<title>Program Ekle</title>
</head>
<body>
	
	<% if @program.errors.any? %>
	<% @program.errors.full_messages.each do |msg| %>
	<%= msg %>
	<% end %>
	<% end %>

	<%= form_for(@program) do |p|%>
	<%= p.label :title%><br />
	<%= p.text_field :title %><br />
	
	<%= p.label :content%><br />
	<%= p.text_area :content %><br />
	
	<%= p.label :active%><br />
	<%= p.text_field :active %><br />
	
	<%= p.submit %>
	
	<% end %>
	
	<%= debug @program %>
	
</body>
</html>

app/views/programs/show.html.erb
<html>
<head>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8">
	<title>Program detay</title>
</head>
<body>
	
	<h1>Program adi: <%= @program.title %></h1>
	<p>Program icerigi: <%= @program.content%></p>
	<p>Program durumnu: 
		
		<% if @program.active %> Aktif
		
		<% else %>Pasif
		<% end %></p>
	
</body>
</html>